export const colors = {
  PRIMARY: '#004CFF',
  PRIMARY_SECONDARY: '#E5EBFC',
  BLACK: '#202020',
  PINK: '#FF5790',
  WHITE: '#FFFFFF',
  WHITE_SECONDARY: '#F3F3F3',
  RED: '#EC4E4E',
  BACKGROUND_ERROR: '#ff3547',
  BACKGROUND_INFO: '#ffa000',
  BACKGROUND_INPUT: '#F8F8F8',
  PINK_SECONDARY: '#FFEBEB',
};
